# Spring Properties
spring:
  cloud:
    config:
      enabled: false
  application:
    name: cart-server
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:mem:test;OLD_INFORMATION_SCHEMA=TRUE;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: update


# HTTP Server
server:
  port: 0   # HTTP (Tomcat) port

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random:uuid}